### ISSUE TITLE
cy.wrap(results) feature request

### ISSUE THREAD

**Issue by msage-godaddy** [cmorten/cypress-web-vitals#12]
# Issue

Setup:

- node version: 16x
- cypress-web-vitals version: 1.0.1

## Details

> This is not a bug. This is a **feature** request. Can you please wrap and return the results as an object, instead of the window, so it can be used and reported for metrics, trending over time, etc. and for console/headless running. Currently the test just 'passes' with no actual value in the output like it does in the cypress app window with the cy.log(result things). See screenshot. 

<img width="1729" alt="feature-request-cy-wrap-results" src="https://user-images.githubusercontent.com/31971850/162270042-90285c52-6c50-4cec-928d-6de54a1d6f87.png">

**Comment by cmorten** [comment]
Sounds good 👍

**Comment by msage-godaddy** [comment]
Thank you :) The only caveat I haven't figured out, is how to report/return the errors too, if it runs into a fault, it doesn't return the object because it throws and returns faster.

**Comment by cmorten** [comment]
The pattern that cypress-audit and other tooling use is to accept an optional callback which receives the results as an argument, which fires before the error is thrown. Would that pattern work here? (Instead of returning the wrapped results)

The alternative would be a flag to optional turn off the lib throwing, but not sure about that…

**Comment by msage-godaddy** [comment]
Possibly - happy to test with you to see if we can get the results as object, just tell me where and I'll test the heck out of it.
